from .modules.args import WanTransformer3DModelArgs
from .modules.model import WanTransformer3DModel
from .modules.state_dict_adapter import WanStateDictAdapter

__all__ = [
    "WanTransformer3DModelArgs",
    "WanTransformer3DModel",
    "WanStateDictAdapter",
    "vdm_wan_2_1_configs",
    "vdm_wan_2_2_configs",
]

vdm_wan_2_1_configs = {
    "t2v_1.3B": WanTransformer3DModelArgs(
        patch_size=(1, 2, 2),
        num_attention_heads=12,
        attention_head_dim=128,
        in_channels=16,
        out_channels=16,
        text_dim=4096,
        freq_dim=256,
        ffn_dim=8960,
        num_layers=30,
        cross_attn_norm=True,
        qk_norm="rms_norm_across_heads",
        eps=1e-6,
        image_dim=None,
        added_kv_proj_dim=None,
        rope_max_seq_len=1024,
        pos_embed_seq_len=None,
        attn_mode="sdpa",
    ),
    "t2v_14B": WanTransformer3DModelArgs(
        patch_size=(1, 2, 2),
        num_attention_heads=40,
        attention_head_dim=128,
        in_channels=16,
        out_channels=16,
        text_dim=4096,
        freq_dim=256,
        ffn_dim=13824,
        num_layers=40,
        cross_attn_norm=True,
        qk_norm="rms_norm_across_heads",
        eps=1e-6,
        image_dim=None,
        added_kv_proj_dim=None,
        rope_max_seq_len=1024,
        pos_embed_seq_len=None,
        attn_mode="sdpa",
    ),
}

vdm_wan_2_2_configs = {
    "ti2v_5B": WanTransformer3DModelArgs(
        patch_size=(1, 2, 2),
        num_attention_heads=24,
        attention_head_dim=128,
        in_channels=48,
        out_channels=48,
        text_dim=4096,
        freq_dim=256,
        ffn_dim=14336,
        num_layers=30,
        cross_attn_norm=True,
        qk_norm="rms_norm_across_heads",
        eps=1e-6,
        image_dim=None,
        added_kv_proj_dim=None,
        rope_max_seq_len=1024,
        pos_embed_seq_len=None,
        attn_mode="sdpa",
    ),
    "t2v_14B": WanTransformer3DModelArgs(
        patch_size=(1, 2, 2),
        num_attention_heads=40,
        attention_head_dim=128,
        in_channels=16,
        out_channels=16,
        text_dim=4096,
        freq_dim=256,
        ffn_dim=13824,
        num_layers=40,
        cross_attn_norm=True,
        qk_norm="rms_norm_across_heads",
        eps=1e-6,
        image_dim=None,
        added_kv_proj_dim=None,
        rope_max_seq_len=1024,
        pos_embed_seq_len=None,
        attn_mode="sdpa",
    ),
    "i2v_14B": WanTransformer3DModelArgs(
        patch_size=(1, 2, 2),
        num_attention_heads=40,
        attention_head_dim=128,
        in_channels=36,
        out_channels=16,
        text_dim=4096,
        freq_dim=256,
        ffn_dim=13824,
        num_layers=40,
        cross_attn_norm=True,
        qk_norm="rms_norm_across_heads",
        eps=1e-6,
        image_dim=None,
        added_kv_proj_dim=None,
        rope_max_seq_len=1024,
        pos_embed_seq_len=None,
        attn_mode="sdpa",
    ),
}
